const fs=require('fs'),vm=require('vm'),assert=require('assert');
require('./profile_import.cjs');
const snapshot=JSON.parse(fs.readFileSync('data/verified_snapshot.json','utf8'));
const additions=JSON.parse(fs.readFileSync('data/reviewed_positions.json','utf8'));for(const j of additions)if(!snapshot.jobs.some(x=>x.id===j.id))snapshot.jobs.push(j);
const source=JSON.parse(fs.readFileSync('sources.json','utf8'));
const context={console,AbortController,Response,Blob,URL,URLSearchParams,TextEncoder,TextDecoder,Uint8Array,Intl,Date,structuredClone,setTimeout,clearTimeout,crypto:require('crypto').webcrypto,localStorage:{getItem(){return null},setItem(){}},document:{querySelector(){return {textContent:'',onclick:null}}},fetch:async()=>new Response(JSON.stringify(snapshot)),location:{hash:'',pathname:'/',search:''},history:{replaceState(){}}};context.window=context;vm.createContext(context);
vm.runInContext(fs.readFileSync('web/matching.js','utf8'),context);
vm.runInContext(fs.readFileSync('web/planning.js','utf8'),context);
vm.runInContext(fs.readFileSync('web/strategy.js','utf8'),context);
vm.runInContext(fs.readFileSync('web/knowledge.js','utf8'),context);
vm.runInContext(fs.readFileSync('web/coverage.js','utf8'),context);
vm.runInContext(fs.readFileSync('web/site_boot.js','utf8'),context);
vm.runInContext('const HANAH_SOURCES='+JSON.stringify(source)+';const HANAH_JOBS='+JSON.stringify(snapshot.jobs)+';',context);
vm.runInContext(fs.readFileSync('web/offline.js','utf8'),context);
(async()=>{const response=await context.fetch('/api/state');const state=await response.json();assert.equal(response.status,200,JSON.stringify(state));assert.equal(state.jobs.length,snapshot.jobs.length);assert.equal(state.sources.length,source.length);
const profile={degree:'硕士',major:'传播学',degree_origin:'境外',party:'是',fresh:'否',graduation_year:'2024',preferred_categories:['辅导员','行政','教辅','专业技术','教师','科研']};
let result=await context.fetch('/api/profile',{body:JSON.stringify(profile)});assert.equal(result.status,200);await context.HANAH_SITE.refresh();
const after=await (await context.fetch('/api/state')).json();assert.equal(after.jobs.length,snapshot.jobs.length);assert.equal(after.profile.major,'传播学');
const trial={id:'trial',school:'测试大学',title:'辅导员',category:'辅导员',source_url:'https://example.com/notice',opens:'2026-10-12',deadline:'2026-10-14T17:00+08:00',status:'即将报名',advice:{date:'2026-10-09'},match:{relevant:true,summary:'需进一步核实',items:[{field:'学历',outcome:'符合'},{field:'语言能力',outcome:'需核实',evidence:'英语六级'}]}};
let strategy=context.HANAH_STRATEGY([trial],profile,'2026-10-10');
assert.equal(strategy.targets.length,1);assert.equal(strategy.tasks.find(t=>t.id.endsWith('::action')).due,'2026-10-12');assert(strategy.tasks.every(t=>t.due>='2026-10-10'));assert(strategy.tasks.every(t=>t.official===trial.deadline));
assert.equal(context.HANAH_STRATEGY([trial],{},'2026-10-10').targets.length,0);
assert.equal(context.HANAH_STRATEGY([{...trial,match:{...trial.match,summary:'不符合'}}],profile,'2026-10-10').targets.length,0);
strategy=context.HANAH_STRATEGY([{...trial,status:'已截止',opens:'2025-04-01',deadline:'2025-04-30',published:'2025-03-20'}],profile,'2026-10-10');assert.equal(strategy.targets[0].kind,'2027储备目标');assert.equal(strategy.targets[0].official,null);assert.equal(strategy.targets[0].observation,null);
const career={tasks:{'trial::x':{done:true,due:'2027-01-01',note:'复盘'}},custom:[{id:'custom:1',title:'试讲',due:'2027-01-10'}],study:{duties:{status:'学习中',answer:1,note:'需要练习'}},settings:{filtersOpen:true}};
let saved=await context.fetch('/api/career',{body:JSON.stringify({state:career})});assert.equal(saved.status,200);await context.HANAH_SITE.refresh();const kept=await (await context.fetch('/api/state')).json();assert.deepEqual(kept.career,career);
saved=await context.fetch('/api/career',{body:JSON.stringify({state:null})});assert.equal(saved.status,400);assert.deepEqual((await (await context.fetch('/api/state')).json()).career,career);
const directory=JSON.parse(fs.readFileSync('data/guangdong_institutions.json','utf8'));const coverage=context.HANAH_COVERAGE(directory,source,after.jobs);assert.equal(coverage.total,167);assert.equal(coverage.configured,53);assert.equal(coverage.rows.find(r=>r.name==='深圳信息职业技术大学').sources.length,1);assert(coverage.verified<coverage.total);
const promotion=kept.jobs.find(j=>j.source_url==='https://www.cuhk.edu.cn/zh-hans/recruitment/20281');assert.equal(promotion.deadline,'2026-10-31');assert.equal(promotion.degree,'本科');assert(promotion.match.items.some(i=>i.field==='语言能力'&&i.outcome==='需核实'));
assert.equal(context.HANAH_LESSONS.length,8);assert(context.HANAH_LESSONS.every(l=>l.options[l.answer]&&l.practice&&l.rubric.length));
const make=(url,date)=>({school:'测试大学',category:'辅导员',title:'辅导员1',source_url:url,opens:date,verification:'原文已核对'});
let plan=context.HANAH_PLANS([make('https://x/a','2026-03-01'),make('https://x/a','2026-03-01')])[0];assert.equal(plan.repeated,false);assert.equal(plan.records.length,1);
plan=context.HANAH_PLANS([make('https://x/a','2025-03-01'),make('https://x/b','2026-04-01')])[0];assert(plan.substantiated);assert.equal(plan.months.join(','),'3,4');
for(const file of fs.readdirSync('web').filter(x=>x.endsWith('.js')))new vm.Script(fs.readFileSync('web/'+file,'utf8'));
const html=fs.readFileSync('site/index.html','utf8');let scripts=[...html.matchAll(/<script>([\s\S]*?)<\/script>/g)];for(const s of scripts)new vm.Script(s[1]);
const exported=await context.fetch('/api/export',{body:JSON.stringify({ids:[state.jobs[0].id]})});assert.equal(exported.status,200);assert((await exported.arrayBuffer()).byteLength>1000);
console.log('PASS: all actual job dates, public snapshot sync, profile persistence, planning recurrence and JS syntax, export.');console.log('Counts',JSON.stringify({total:after.jobs.length,current:after.jobs.filter(j=>j.deadline&&j.deadline.slice(0,10)>=after.today).length,shortlist:after.jobs.filter(j=>j.deadline&&j.deadline.slice(0,10)>=after.today&&j.match.relevant&&j.match.summary!=='不符合').map(j=>[j.school,j.title])}));
})().catch(e=>{console.error(e.message);process.exit(1)});

