let careerModel,careerBound=false,studyTrack='全部',wrongOnly=false;
function careerState(){return structuredClone(window.HANAH_CAREER(data.career))}
async function saveCareer(next){await api('career',{state:next});data.career=next;render()}
function renderCareerPlanning(){
 careerModel=window.HANAH_STRATEGY(data.jobs,data.profile,data.today,data.career);
 const {ready,targets,tasks,chosen}=careerModel,age=data.profile.birth_date?`${2027-Number(data.profile.birth_date.slice(0,4))-1}–${2027-Number(data.profile.birth_date.slice(0,4))}周岁`: '待填写生日';
 $('#planSummary').textContent=ready?`按你的档案初筛：${targets.filter(t=>t.kind==='当前投递'&&!t.barrier).length} 个当前投递目标；${chosen.length} 个目标进入待办。2027年龄 ${age}，新公告发布后须重核年龄计算日与所有资格。`:'先在「我的报考条件」保存学历与专业，才能生成个性化推荐；学习库与自建待办可直接使用。';
 $('#taskStats').textContent=`${tasks.filter(t=>t.done).length} / ${tasks.length} 项完成 · ${tasks.filter(t=>!t.done&&t.due<data.today).length} 项已过建议日期`;
 $('#todoList').innerHTML=tasks.map(t=>`<article class="todo ${t.done?'done':''}"><label class="todoCheck"><input type="checkbox" data-task-check="${esc(t.id)}" ${t.done?'checked':''}><strong>${esc(t.title)}</strong></label><small>${esc(t.school||'我的任务')} ${esc(t.role||'')} · ${esc(t.dueKind)} ${esc(t.due||'未设置')} ${!t.done&&t.due<data.today?'· 请调整计划':''}${t.official&&t.due>t.official.slice(0,10)?' · 建议日期晚于官方截止，请提前':''}</small>${t.official?`<small class="official">官方报名截止 ${esc(showDate(t.official))}（不能随建议日期调整）</small>`:''}<details><summary>任务说明与笔记</summary><p class="preserve">${esc(t.detail||'')}</p>${t.note?`<p class="preserve">我的笔记：${esc(t.note)}</p>`:''}${t.url?`<a href="${safeLink(t.url)}" target="_blank" rel="noopener">核对官方公告 ↗</a>`:''}</details><div class="actions"><button data-task-edit="${esc(t.id)}">修改日期／笔记</button>${t.track?`<button data-start-track="${esc(t.track)}">学习对应方向</button>`:''}${t.custom?`<button data-task-delete="${esc(t.id)}">删除</button>`:''}</div></article>`).join('')||'<p class="muted">把推荐目标加入待办，或新增自己的任务。</p>';
 const visible=targets.filter(t=>!$('#planMine').checked||!t.barrier);
 $('#planCards').innerHTML=visible.map((t,i)=>`${i===0||visible[i-1].kind!==t.kind||visible[i-1].date.slice(0,7)!==t.date.slice(0,7)?`<h3 class="timelineHeading">${esc(t.date.slice(0,7))} · ${esc(t.kind)}</h3>`:''}<article class="planCard"><span class="badge ${t.barrier?'warn':''}">${esc(t.barrier?'先核实关键资格':t.kind)}</span><h3>${esc(t.school)} · ${esc(t.title)}</h3><small>${esc(t.nature||'')} · ${esc(t.school_level||'')} · ${esc(t.category)}</small><strong>${esc(t.kind==='当前投递'?`官方截止 ${showDate(t.official)}`:t.observation?`${t.date.slice(0,7)} 起重点关注`:'个人准备目标 '+t.date)}</strong><p>推荐依据：${esc(t.reasons.join('、')||'方向相关，资格仍待核实')}。${esc(t.job.match.summary)}。</p><p class="muted">${esc(t.uncertain.map(i=>i.field).join('、')||'')}${t.uncertain.length?'仍需确认。':''}</p><details><summary>资格差距、材料与历史时间线</summary><p class="preserve">${esc(t.uncertain.map(i=>i.field+'：'+i.evidence).join('\n'))}</p><p class="preserve">${esc(t.job.materials||'材料清单待核对原文附件')}</p>${t.records.map(r=>`<p><a href="${safeLink(r.url)}" target="_blank" rel="noopener">${esc(r.date)} · ${esc(r.basis)} ↗</a><small>开始 ${esc(showDate(r.opens))} · 截止 ${esc(showDate(r.deadline))}</small></p>`).join('')}<p>${esc(t.signal)}；${esc(t.window)}。2027岗位、名额和条件尚未确认；单年记录只用于储备，不能预测再次招聘。</p></details><div class="actions"><button data-pin-target="${esc(t.key)}">${t.pinned?'移出自选目标':chosen.includes(t)?'固定为自选目标':'加入我的待办'}</button><button data-detail="${esc(t.job.id)}">岗位详情</button></div></article>`).join('')||'<p class="muted">暂无符合档案初筛的目标。可检查档案或院校覆盖中的待核验公告。</p>';
}
function renderLearning(){
 const s=careerState().study,all=window.HANAH_LESSONS,lessons=all.filter(l=>(studyTrack==='全部'||l.track===studyTrack||l.track==='通用')&&(!wrongOnly||s[l.id]?.answer!=null&&Number(s[l.id].answer)!==l.answer));
 $('#studySummary').textContent=`${all.filter(l=>s[l.id]?.status==='已掌握').length} / ${all.length} 张知识卡已掌握 · ${all.filter(l=>s[l.id]?.answer!=null&&Number(s[l.id].answer)!==l.answer).length} 道练习待复习。每张卡包含知识、练习、参考点评和可保存笔记。`;
 document.querySelectorAll('[data-study-track]').forEach(b=>b.classList.toggle('active',b.dataset.studyTrack===studyTrack));
 $('#wrongOnly').checked=wrongOnly;
 $('#lessonCards').innerHTML=lessons.map(l=>{const p=s[l.id]||{},answered=p.answer!=null;return `<article class="lesson"><span class="badge">${esc(l.track)} · 建议 ${l.minutes} 分钟</span><h3>${esc(l.title)}</h3><ul>${l.points.map(x=>`<li>${esc(x)}</li>`).join('')}</ul><details><summary>做一道自编练习${answered?' · 已作答':''}</summary><p>${esc(l.question)}</p><div class="quiz">${l.options.map((o,i)=>`<button data-answer-lesson="${l.id}" data-answer-index="${i}" class="${answered&&Number(p.answer)===i?'selected':''}">${String.fromCharCode(65+i)}. ${esc(o)}</button>`).join('')}</div>${answered?`<p role="status" class="feedback">${Number(p.answer)===l.answer?'回答正确':'还需复习'} · 参考答案 ${String.fromCharCode(65+l.answer)}。${esc(l.explain)}</p>`:''}</details><details><summary>案例／实操练习与自评</summary><p>${esc(l.practice)}</p><p>自评检查：${esc(l.rubric.join('；'))}。</p><small>案例与点评是自编学习材料，并非招聘真题或官方评分标准。</small></details>${l.refs.map(r=>`<a href="${safeLink(r.url)}" target="_blank" rel="noopener">${esc(r.title)} ↗</a>`).join('')}<label>学习进度<select data-study-status="${l.id}">${['未开始','学习中','已掌握'].map(v=>`<option ${p.status===v?'selected':''}>${v}</option>`).join('')}</select></label>${p.note?`<p class="preserve notePreview">${esc(p.note.slice(0,160))}</p>`:''}<button data-lesson-note="${l.id}">${p.note?'编辑学习笔记':'写学习笔记'}</button></article>`}).join('')||'<p>当前没有待复习题目。可切换方向或先完成练习。</p>';
}
function initCareerUi(){
 const filter=$('#filterPanel');$('#filterStateSummary').textContent=`${{current:'当前投递',leads:'长期线索',history:'历史资料',all:'全部记录'}[scope]} · ${[...filters,'query','major'].filter(f=>f==='query'||f==='major'?$('#'+f).value.trim():selected(f).length).length} 项筛选 · ${filtered.length} 个结果`;
 if(careerBound)return;careerBound=true;filter.open=!!careerState().settings.filtersOpen;
 filter.addEventListener('toggle',async()=>{try{const next=careerState();if(next.settings.filtersOpen===filter.open)return;next.settings={...next.settings,filtersOpen:filter.open};await api('career',{state:next});data.career=next}catch(e){message(e.message)}});
 $('#wrongOnly').onchange=e=>{wrongOnly=e.target.checked;renderLearning()};
 document.body.addEventListener('change',async e=>{try{const next=careerState(),el=e.target;if(el.dataset.taskCheck){const id=el.dataset.taskCheck,t=next.custom.find(t=>t.id===id);if(t)t.done=el.checked;else next.tasks={...next.tasks,[id]:{...next.tasks[id],done:el.checked}};await saveCareer(next)}if(el.dataset.studyStatus){const id=el.dataset.studyStatus;next.study={...next.study,[id]:{...next.study[id],status:el.value}};await saveCareer(next)}}catch(err){message(err.message)}});
 document.body.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;try{
  const next=careerState();if(b.dataset.pinTarget){const key='pin:'+b.dataset.pinTarget;next.settings={...next.settings,[key]:!next.settings[key]};await saveCareer(next)}
  if(b.dataset.startTrack){studyTrack=b.dataset.startTrack;tab='learning';render()}
  if(b.dataset.studyTrack){studyTrack=b.dataset.studyTrack;renderLearning()}
  if(b.dataset.answerLesson){const id=b.dataset.answerLesson;next.study={...next.study,[id]:{...next.study[id],answer:Number(b.dataset.answerIndex)}};await saveCareer(next)}
  if(b.dataset.taskDelete){next.custom=next.custom.filter(t=>t.id!==b.dataset.taskDelete);await saveCareer(next)}
  if(b.id==='addTodo'||b.dataset.taskEdit){const t=careerModel?.tasks.find(t=>t.id===b.dataset.taskEdit)||{},f=$('#careerForm');f.dataset.mode='task';f.dataset.id=t.id||'';$('#careerTitle').textContent=t.id?'编辑任务':'新增我的任务';$('#careerName').value=t.title||'';$('#careerDue').value=t.due||data.today;$('#careerNote').value=t.note||'';$('#careerName').readOnly=!!t.id&&!t.custom;$('#careerDueLabel').hidden=false;$('#careerNameLabel').hidden=false;$('#careerDialog').showModal()}
  if(b.dataset.lessonNote){const id=b.dataset.lessonNote,f=$('#careerForm');f.dataset.mode='study';f.dataset.id=id;$('#careerTitle').textContent=window.HANAH_LESSONS.find(l=>l.id===id).title+' · 学习笔记';$('#careerNameLabel').hidden=true;$('#careerDueLabel').hidden=true;$('#careerNote').value=next.study[id]?.note||'';$('#careerDialog').showModal()}
  if(b.id==='exportPlan'){const blob=new Blob([JSON.stringify({exported:data.today,profileIncluded:false,tasks:careerModel.tasks,targets:careerModel.chosen.map(t=>({school:t.school,title:t.title,kind:t.kind,date:t.date,official:t.official})),study:next.study},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='岸上备考计划-'+data.today+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
 }catch(err){message(err.message)}});
 $('#careerForm').onsubmit=async e=>{e.preventDefault();try{const f=e.target,next=careerState(),id=f.dataset.id;if(f.dataset.mode==='study')next.study={...next.study,[id]:{...next.study[id],note:$('#careerNote').value}};else {if(!$('#careerName').value.trim())throw Error('请填写任务名称');const patch={due:$('#careerDue').value,note:$('#careerNote').value};if(id&&!next.custom.some(t=>t.id===id))next.tasks={...next.tasks,[id]:{...next.tasks[id],...patch}};else if(id)next.custom=next.custom.map(t=>t.id===id?{...t,...patch,title:$('#careerName').value}:t);else next.custom=[...next.custom,{id:'custom:'+crypto.randomUUID(),title:$('#careerName').value,...patch,done:false}]};await saveCareer(next);$('#careerDialog').close()}catch(err){message(err.message)}};
}
