// Local adapter for the standalone edition. No network scraping or cross-device synchronization.
(()=>{
const site=window.HANAH_SITE;
const key=site?.storageKey||(typeof HANAH_PROFILE!=='undefined'?'hanah-library-wyh-v2':typeof HANAH_JOBS==='undefined'?'hanah-library-offline-v1':'hanah-library-real-v1'), hosts=HANAH_SOURCES.map(s=>new URL(s.url).hostname);
const stamp=()=>new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Shanghai',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const seed=()=>({version:1,jobs:typeof HANAH_JOBS==='undefined'?[]:structuredClone(HANAH_JOBS),profile:typeof HANAH_PROFILE==='undefined'?{}:structuredClone(HANAH_PROFILE),sources:HANAH_SOURCES.map(s=>site?{...s}:{...s,error:'离线版不自动检查官网，请打开原站核对公告。'}),notices:[]});
let store;try{store=JSON.parse(localStorage.getItem(key)||'null')||seed()}catch{store=seed()}
if(typeof HANAH_JOBS!=='undefined'){const ids=new Set(store.jobs.map(j=>j.id));store.jobs.push(...structuredClone(HANAH_JOBS).filter(j=>!ids.has(j.id)))}
if(site&&typeof HANAH_PROFILE!=='undefined'&&HANAH_PROFILE?.name&&!store.profile?.name)store.profile=structuredClone(HANAH_PROFILE);
function persist(next){if(site)next=site.compact(next);try{localStorage.setItem(key,JSON.stringify(next))}catch{throw Error('浏览器无法保存本地数据，请改用普通模式的 Chrome / Edge，并下载备份。')}store=next}
function date(s){if(!s)return null;const normalized=s.replace(' ','T');const d=new Date(normalized.length===10?normalized+'T00:00:00+08:00':/([zZ]|[+-]\d\d:\d\d)$/.test(normalized)?normalized:normalized+'+08:00');if(!Number.isFinite(d.getTime()))throw Error('日期格式无效，请使用 YYYY-MM-DD 或 YYYY-MM-DDTHH:mm');return d}
function format(d,exact){const offset=new Date(d.getTime()+8*3600000).toISOString();return offset.slice(0,exact?16:10)+(exact?'+08:00':'')}
function advice(j){if(j.rolling)return {date:null,reason:'滚动招聘 / 招满即止，建议尽快投递'};const end=date(j.deadline);if(!end)return {date:null,reason:'截止时间待核实'};let days=j.review_required?5:3,reason=`官方截止前${days}天，预留提交与审核时间`;if(j.method==='邮寄'){if(!['寄出','送达'].includes(j.mail_rule))return {date:null,reason:'邮寄截止按寄出还是送达计算，需核实'};if(j.mail_rule==='送达'&&!j.shipping_days)return {date:null,reason:'请填写预计物流天数后计算'};days=(j.mail_rule==='送达'?Number(j.shipping_days):0)+2;reason=`按${j.mail_rule}期限，物流与缓冲共${days}天`}let result=new Date(end-days*86400000);const material=date(j.material_deadline),opening=date(j.opens);if(material&&material<result){result=material;reason+='；采用更早的材料提交期限'}if(opening&&opening>result){result=opening;reason+='；报名窗口较短，建议开放后尽快投递'}const exact=j.deadline.length>10;return {date:format(result,exact),reason:reason+(exact?'':'；官方未明确截止时刻，请提前完成')}}
function status(j){if(j.cancelled)return '已取消';if(j.deadline_variants?.length&&j.deadline_variants.every(d=>d.slice(0,10)<stamp()))return '已截止';const end=date(j.deadline);if(end&&(j.deadline.length===10?j.deadline<stamp():end<new Date()))return '已截止';if(j.rolling)return '滚动招聘';const opening=date(j.opens);if(opening&&opening>new Date())return '即将报名';return end?'正在报名':'截止待核实'}
function match(j,p){if(p.birth_date||p.degree_origin)return window.HANAH_MATCH(j,p,stamp(),status(j));const rank={'高中':-1,'大专':0,'本科':1,'硕士':2,'博士':3};const items=[['degree','学历'],['major','专业'],['age','年龄'],['party','党员'],['fresh','应届身份'],['establishment','编制']].map(([field,label])=>{let outcome='需核实',evidence=j.evidence?.[field]||'未录入对应原文',v=p[field];if(evidence!=='未录入对应原文'){if(field==='degree'&&v in rank&&j.degree in rank)outcome=rank[v]>=rank[j.degree]?'符合':'不符合';if(field==='major'&&v&&j.majors?.length)outcome=j.majors.includes(v)||j.majors.includes('不限')?'符合':'需核实';if(field==='party'&&['是','否'].includes(v)&&j.party_required!=null)outcome=j.party_required&&v==='否'?'不符合':'符合'}if(field==='establishment'&&v)outcome=v==='不限'||v===j.establishment?'符合':j.establishment?'不符合':'需核实';return {field:label,outcome,evidence}});return {items,summary:items.some(i=>i.outcome==='不符合')?'不符合':items.some(i=>i.outcome==='需核实')?'需进一步核实':'符合已知条件'}}
function reminders(j){const notes=[];if(!['已报名','待考试','已结束'].includes(j.personal?.stage)&&!['已截止','已取消'].includes(j.status)){if(j.deadline){const days=Math.round((date(j.deadline.slice(0,10))-date(stamp()))/86400000);if([7,3,1,0].includes(days))notes.push(`距官方截止${days}天`)}if(j.advice.date){const d=j.advice.date.slice(0,10);if(d===stamp())notes.push('今天是建议投递日');else if(d<stamp())notes.push('已过建议时间，仍可报名，请尽快提交')}}if(j.changes?.length)notes.push('岗位有变更，请查看记录');if(j.exam_date){const d=Math.round((date(j.exam_date.slice(0,10))-date(stamp()))/86400000);if(d>=0&&d<=3)notes.push('考试临近，请确认安排')}return notes}
function computed(){return {...structuredClone(store),coverage:{schools:[...new Set(store.jobs.filter(j=>['原文已核对','已核验'].includes(j.verification)).map(j=>j.school))],cities:[...new Set(store.jobs.filter(j=>['原文已核对','已核验'].includes(j.verification)).map(j=>j.city))]},today:stamp(),jobs:store.jobs.map(raw=>{const j=structuredClone(raw);if(site)site.expand(j,store);j.personal??={};j.changes??=[];j.status=status(j);j.advice=advice(j);j.match=match(j,store.profile);j.reminders=reminders(j);return j})}}
function validate(j){for(const k of ['school','title','source_url'])if(typeof j[k]!=='string'||!j[k].trim())throw Error('缺少 '+k);let u;try{u=new URL(j.source_url)}catch{throw Error('官方链接无效')}if(u.protocol!=='https:'||!hosts.includes(u.hostname))throw Error('来源须为已登记官方域名的 HTTPS 链接');for(const k of ['deadline','opens','material_deadline','exam_date'])date(j[k]);if(Number(j.shipping_days||0)<0)throw Error('物流天数不得为负')}
function localApi(path,body){if(path==='state')return computed();if(path==='refresh'){if(site)return site.refresh();throw Error('离线版无法自动采集，请在来源监测页打开官方链接手动核对。');}const next=structuredClone(store);if(path==='profile')next.profile=body;else if(path==='personal'){const j=next.jobs.find(j=>j.id===body.id);if(!j)throw Error('岗位不存在');j.personal=body}else if(path==='jobs'){validate(body);const old=next.jobs.find(j=>body.id?j.id===body.id:j.source_url===body.source_url&&j.title===body.title&&String(j.code||'')===String(body.code||''));const j={...body,id:old?.id||body.id||crypto.randomUUID(),province:body.province||'广东省',nature:body.nature||'公办',salary:body.salary||'公告未披露',verification:body.verification||'待核验',personal:old?.personal||{},changes:old?.changes||[]};if(site)j._local_edit=true;if(old)j.changes.push({at:new Date().toISOString(),text:'岗位记录已编辑，请对照公告核实'});if(j.verification==='已核验')j.last_verified=new Date().toISOString();next.jobs=next.jobs.filter(x=>x.id!==j.id);next.jobs.push(j);persist(next);return {id:j.id}}else throw Error('离线版未支持此操作');persist(next);return {ok:true}}
function xml(v){return String(v??'未公布').replace(/[\x00-\x08\x0b\x0c\x0e-\x1f]/g,'').replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]))}
const enc=new TextEncoder();function zip(files){const local=[],central=[];let offset=0;const u16=(v,a,n)=>new DataView(a.buffer).setUint16(n,v,true),u32=(v,a,n)=>new DataView(a.buffer).setUint32(n,v,true);function crc(raw){let c=-1;for(const b of raw){c^=b;for(let i=0;i<8;i++)c=(c>>>1)^((c&1)?0xedb88320:0)}return (c^-1)>>>0}for(const [name,text]of Object.entries(files)){const n=enc.encode(name),b=enc.encode(text),checksum=crc(b),l=new Uint8Array(30+n.length);u32(0x04034b50,l,0);u16(20,l,4);u32(checksum,l,14);u32(b.length,l,18);u32(b.length,l,22);u16(n.length,l,26);l.set(n,30);local.push(l,b);const c=new Uint8Array(46+n.length);u32(0x02014b50,c,0);u16(20,c,4);u16(20,c,6);u32(checksum,c,16);u32(b.length,c,20);u32(b.length,c,24);u16(n.length,c,28);u32(offset,c,42);c.set(n,46);central.push(c);offset+=l.length+b.length}const e=new Uint8Array(22);u32(0x06054b50,e,0);u16(central.length,e,8);u16(central.length,e,10);u32(central.reduce((a,b)=>a+b.length,0),e,12);u32(offset,e,16);return new Blob([...local,...central,e],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'})}
function workbook(ids){const cols=[['school','院校'],['province','省份'],['city','城市'],['district','区县'],['title','岗位'],['requirements','岗位要求'],['conditions','报名条件'],['salary','薪资'],['deadline','官方截止'],['suggested','建议投递'],['source_url','官方链接'],['note','备注'],['status','报名状态'],['match_summary','个人资格初筛'],['match_priority','个人优先级']];const rows=[cols.map(x=>x[1]),...computed().jobs.filter(j=>ids.includes(j.id)).map(j=>cols.map(([k])=>k==='match_summary'?j.match.summary:k==='match_priority'?j.match.priority:k==='suggested'?j.advice.date:k==='note'?j.personal.note:j[k]))];const sheet='<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetData>'+rows.map((row,i)=>`<row r="${i+1}">`+row.map(v=>`<c t="inlineStr"><is><t>${xml(v)}</t></is></c>`).join('')+'</row>').join('')+'</sheetData></worksheet>';return zip({'[Content_Types].xml':'<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/></Types>','_rels/.rels':'<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>','xl/workbook.xml':'<workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="招聘岗位" sheetId="1" r:id="rId1"/></sheets></workbook>','xl/_rels/workbook.xml.rels':'<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/></Relationships>','xl/worksheets/sheet1.xml':sheet})}
window.fetch=async(url,options={})=>{try{if(!String(url).startsWith('/api/'))throw Error('离线版没有后台连接');const path=String(url).slice(5),body=JSON.parse(options.body||'{}');if(path==='export')return new Response(workbook(body.ids||[]));return new Response(JSON.stringify(await localApi(path,body)),{headers:{'Content-Type':'application/json'}})}catch(e){return new Response(JSON.stringify({error:e.message}),{status:400,headers:{'Content-Type':'application/json'}})}};
function download(blob,name){const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
document.querySelector('#backup').onclick=()=>download(new Blob([JSON.stringify(store,null,2)],{type:'application/json'}),'岸上备份-'+stamp()+'.json');document.querySelector('#restore').onclick=()=>document.querySelector('#backupFile').click();document.querySelector('#backupFile').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{if(f.size>10_000_000)throw Error('备份过大');const next=JSON.parse(await f.text());if(next.version!==1||!Array.isArray(next.jobs)||!next.profile||typeof next.profile!=='object')throw Error('不是有效的岸上备份');next.jobs.forEach(validate);next.sources=seed().sources;next.notices=[];if(!confirm('恢复将覆盖此浏览器当前的岗位和个人记录。是否继续？'))return;persist(next);location.reload()}catch(err){document.querySelector('#alert').textContent=err.message}finally{e.target.value=''}};
if(site){site.attach({get:()=>store,persist,validate});try{persist(store)}catch(e){document.querySelector('#alert').textContent=e.message}}
document.querySelector('.dot').textContent=site?'官方快照同步 · 个人数据仅存本浏览器':'离线手动维护 · 数据保存在此浏览器';document.querySelector('.brand').href='#';document.querySelector('#profileDialog .muted').textContent='保存在当前浏览器，可随时修改；请定期备份。';document.querySelector('#sourcesPanel .sub').textContent='离线版提供官方来源入口，不自动抓取、核验或跨设备同步。数据更新需要你手动维护。';
})();
